Outputs:
  UserPoolId:
    Value: !Ref UserPool
  UserPoolProviderName:
    Value: !GetAtt UserPool.ProviderName
  UserPoolClientId:
    Value: !Ref UserPoolClient
  IdentityPoolId:
    Value: !Ref IdentityPool
  PremiumContentBucketName:
    Value: !Ref PremiumContentBucket
  FreeContentBucketName:
    Value: !Ref FreeContentBucket
