Outputs:
  userPoolId:
    Value: !Ref UserPool
  userPoolClientId:
    Value: !Ref UserPoolClient
  identityPoolId:
    Value: !Ref IdentityPool
  premiumContentBucketName:
    Value: !Ref PremiumContentBucket
  freeContentBucketName:
    Value: !Ref FreeContentBucket
